rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/',views.about, name='about'),
    path('category/<slug:category_name_slug>/',
        views.show_category,name='show_category'),
    path('add_category/',views.add_category,name='add_category'),
    path('category/<slug:category_name_slug>/add_page/',views.add_page,name='add_page'),
    path('restricted/',views.restricted,name='restricted'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views

urlpatterns = [
    path('',views.index,name='index'),
    path('rango/', include('rango.urls')),
    # The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
    path('accounts/',include('registration.backends.simple.urls'))
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    NAME_MAX_LENGTH=128

    name = models.CharField(max_length=NAME_MAX_LENGTH,unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug =models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug=slugify(self.name)
        super(Category,self).save(*args,**kwargs)

    class Meta:
        verbose_name_plural = 'Categories'
    def __str__(self):
        return self.name

class Page(models.Model):
    TITLE_MAX_LENGTH=128
    URL_MAX_LENGTH=200


    category = models.ForeignKey(Category,  on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return str(self.title)

class UserProfile(models.Model):
    user =models.OneToOneField(User,on_delete=models.CASCADE)
    website =models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images',blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page,Category, UserProfile

class CategoryForm(forms.ModelForm):
    name=forms.CharField(max_length=Category.NAME_MAX_LENGTH,
                        help_text="Please enter the category name.")
    views=forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    likes=forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    slug=forms.CharField(widget=forms.HiddenInput(),required=False)

    class Meta:
        model=Category
        fields=('name',)

class PageForm(forms.ModelForm):

    def clean(self):
        cleaned_data = self.cleaned_data
        url=cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
       
        return cleaned_data

    title=forms.CharField(max_length=128,
                        help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=Page.TITLE_MAX_LENGTH,
                        help_text="Please enter the URL of the page.")
    views=forms.IntegerField(widget=forms.HiddenInput(),initial=0)


    class Meta:
        model=Page

        exclude = ('category',)

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model=UserProfile
        fields = ('website','picture',)

rango/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from rango.models import Category,Page
from rango.forms import CategoryForm,PageForm,UserForm, UserProfileForm
from django.urls import reverse
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from datetime import datetime

# Create your views here.

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    visitor_cookie_handler(request)

    return render(request, 'rango/index.html', context=context_dict)

def visitor_cookie_handler(request):
    # Get the number of visits to the site.
    # We use the COOKIES.get() function to obtain the visits cookie.
    # If the cookie exists, the value returned is casted to an integer.
    # If the cookie doesn't exist, then the default value of 1 is used.
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request,'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days >0:
        visits = visits+1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits']= visits

def get_server_side_cookie(request,cookie,default_val=None):
    val = request.session.get(cookie)
    if not val:
        val=default_val
    return val

def about(request):

    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits']= request.session['visits']

    return render(request, 'rango/about.html', context=context_dict)

def show_category(request,category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # The .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        # Retrieve all of the associated pages.
        # The filter() will return a list of page objects or an empty list.
        pages = Page.objects.filter(category=category)
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None
    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method =='POST':
        form = CategoryForm(request.POST)

        #have we been provided with a valid form
        if form.is_valid():

            #Save the new category to the database
            cat = form.save(commit=True)
            print(cat, cat.slug)
            #redircet back to index view
            return redirect('/rango/')
        else:
            #the form contained errors
            print(form.errors)
    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html',{'form':form})

@login_required
def add_page(request,category_name_slug):
    try:
        category=Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category=None
    
    if category is None:
        return redirect('/rango/')
    
    form=PageForm()

    if request.method =='POST':
        form=PageForm(request.POST)

        if form.is_valid():
            if category:
                page =form.save(commit=False)
                page.category = category
                page.views =0
                page.save()

                return redirect(reverse('rango:show_category',kwargs={'category_name_slug':category_name_slug}))
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

@login_required
def restricted(request):
    return render(request,'rango/restricted.html')

    # return HttpResponse("Since you're logged in, you can see this text!")

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %} <!-- New line -->

{% block title_block %}
    About Rango
{% endblock %}
{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        here is the about page. <br />
        <strong>This tutorial has been put together by Robert Nimmo</strong><br />
    </div>
    <div>
        <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />
    </div>
    <div>
        <p>Visits: {{ visits }}</p>
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends "rango/base.html" %}
{% block title %}Add a Category{% endblock %}
{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Category</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">
                Create Category
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% block title %}Add Page{% endblock %}
{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Page to {{category.name}}</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}<br />
            <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">
                Add Page
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/rango/base-old.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head>
        <title>
            Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                <li><a href="{% url 'auth_password_change' %}">Change your Password</a></li>
            {% else %}
                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>
    
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>
                
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
                    {% block body_block %}{% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

templates/rango/categories.html
<ul class="nav flex-column">
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li class="nav-item">
        <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
            <span data-feather="archive"></span>{{ c.name }}
        </a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
            <span data-feather="archive"></span>{{ c.name }}
        </a>
        </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li class="nav-item">There are no categories present.</li>
{% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
    <h1>{{ category.name }}</h1>
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{{page.url}}">{{ page.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}
    {% if user.is_authenticated %}
    <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
    {% endif %}
    {% else %}
    The specified category does not exist.
    {% endif %}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
<!-- New line -->

{% block title_block %}
Homepage
{% endblock %}

{% block body_block %}

<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Rango says...</h1>
        <div>
            <h2 class="h2">
                {% if user.is_authenticated %}
                howdy {{ user.username }}!
                {% else %}
                hey there partner!
                {% endif %}
            </h2>
            <strong>{{ boldmessage }}</strong>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Most Liked Categories</h2>
                    <p class="card-text">
                        {% if categories %}
                        <ul>
                            {% for category in categories %}
                            <li class="list-group-item">
                                <a href="{% url 'rango:show_category' category.slug %}">
                                    {{ category.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                        {% else %}
                        <strong>There are no categories present.</strong>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Most Viewed Pages</h2>
                    <p class="card-text">
                        {% if pages %}
                        <ul>
                            {% for page in pages %}
                            <li class="list-group-item">
                                <a href="{{ page.url }}">{{ page.title }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                        {% else %}
                        <strong>There are no pages present.</strong>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
    Since you're logged in, you can see this text!
{% endblock %}